### PR TITLE
Plane

### PR DESCRIPTION
**Pull request by foglienimatteo**
This is a WIP branch at the end of which will be implemented the following features:

- [x] struct Plane and connected functions
- [x] tests for all of them
- [x] a subdivision of the `runtests.jl` file

### CODE REVIEW

**Comment by foglienimatteo** [comment]
@all-contributors please add @ziotom78 for mentoring

**Comment by foglienimatteo** [comment]
@all-contributors please add @Paolo97Gll and @Samuele-Colombo for tool and ideas

**Comment by Samuele-Colombo** [comment]
Ciao Matteo,
che sta succedendo esattamente? Mi sono perso qualcosa? Perchè sono 
stato citato nella tua PR #11?

-- 
Samuele Colombo

**Comment by Samuele-Colombo** [comment]
Sorry, I did not know that responding to the mail would post a comment in the PR

**Comment by foglienimatteo** [comment]
> Sorry, I did not know that responding to the mail would post a comment in the PR

I've simply used [all-contributors](https://github.com/all-contributors/app) to get a better `Contributors` section into the `README.md` file. I tagged you and Paolo because I curiously looked to your Raytracer program implementation, and that gave me lots of ideas and solutions for the problems we got to deal with (particularly the CLI for Julia and the SVector for the optimization of Transformation*Vector product).

I also notice that all-contributors didn't work for your name, so I recall it:
@all-contributors please add @Samuele-Colombo for tool and ideas

**Comment by Samuele-Colombo** [comment]
Ok, thanks for inviting, then!

**Pull request merged**
